### ISSUE TITLE
502 error occurs with requests containing > 60 items 

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/request_broker#116]
## Describe the bug
When the number of requested items is large (greater than about 60-65 items), the system shows a 502 error and the user sees that their request failed. However, the request WILL eventually go through.

## To reproduce
1. Add 65+ items to My List in DIMES
2. Email all items (or other requests like Download or request)
3. Wait as "Adding items to your message..." modal displays
4. See 502 error
5. Email will be delivered anyway

## Expected behavior
A request involving a large number of items will be successful, even if it takes more time to complete.

## Error message or screenshots
In console: "Failed to load resource: the server responded with a status of 502 (Proxy Error)"
![image](https://user-images.githubusercontent.com/15254041/109719607-e3044f80-7b76-11eb-803e-4783010705bf.png)

## Impact on your work
Two users have reported this issue in ~3 weeks, so a list of this size appears to be a somewhat common occurrence. Creates confusion that the request failed, even if it eventually comes through.

**Comment by helrond** [comment]
I think the best solution here is to try and improve the speed of the `get_data` method, which should alleviate this problem but also improve performance overall.

Since this is only happening with email, we could also send a response and then handle the actual sending of the email in a callback. The problem with that is that approach is that the sending might not be successful, and we want to provide feedback to the user about that.

Benchmarking:
- Request with 100 objects (`archival_objects/1` - `archival_objects/101`) takes about 1:30 to complete.
