### ISSUE TITLE
Process Request Parsing fails if Archival Object has no Instance

### ISSUE THREAD

**Issue by ctgraham** [RockefellerArchiveCenter/request_broker#325]
## Describe the bug
When an Archival Object in ASpace has no Instance, it can be indexed by DIMES, but adding it to My List causes an error when Request Broker parses the object.

`is_submittable()` assumes the `preferred_instance` `format` must be able to be lowercased.

https://github.com/RockefellerArchiveCenter/request_broker/blob/6578e594973679133e023b72ad23f3b5ec2e6a20/process_request/routines.py#L112C14-L112C50

But, `get_preferred_format()` allows for the case where there is no instances, and all properties are set to `None`.
https://github.com/RockefellerArchiveCenter/request_broker/blob/6578e594973679133e023b72ad23f3b5ec2e6a20/process_request/helpers.py#L162-L171

## To reproduce
1. Create an ASpace object with no instance
2. Add the object to My List
3. Open My List
4. See error.

## Expected behavior
Graceful failure, or no failure in the case where an Archival Object has no Instance.

## Error message or screenshots

```
There was an error fetching data.

The request to https://[requst-broker.DOMAIN]/api/process-request/parse failed.

To report this problem, send us an email at archives-ref@[DOMAIN].

Error message:

ERR_BAD_RESPONSE: Request failed with status code 500

{"detail":"'NoneType' object has no attribute 'lower'"}

Request data:

{"item":"/repositories/10/archival_objects/515357"}
```
## Impact on your work
This presents a failure message to the end user.

## Additional context
Initially I wondered if this should be considered a data error, but the code allows for the condition of `None` being passed through, and it seems like we want these object to be indexed.

**Comment by helrond** [comment]
Initially I was super confused because this is a scenario that is accounted for in `is_submittable` (see https://github.com/ulsdevteam/request_broker/blob/main/process_request/routines.py#L104-L105) and is also tested (https://github.com/ulsdevteam/request_broker/blob/main/process_request/tests.py#L275-L280).

However, I was able to reproduce this, and what's happening here is that the `strip_tags` method is converting `None` into `'None'` (i.e. a string) so in cases where there's no instances you get a `preferred_instances` dict that looks like:
```
{'format': None, 'container': 'None', 'subcontainer': 'None', 'location': 'None', 'barcode': None, 'uri': None}
```
I'm thinking the cleanest way to handle this is just to add a check in `strip_tags` so that if the `user_string` is `None` to just return it?

**Comment by ctgraham** [comment]
Yes, that makes sense to me.
