### ISSUE TITLE
Clean up email line breaks

### ISSUE THREAD

**Issue by HaSistrunk** [RockefellerArchiveCenter/request_broker#97]
## Is your feature request related to a problem? Please describe.
- There should be a blank line between the email message and the first item title
- The URL needs to be in a new line
- The `Creator/s` label is currently a link, but should not be (unless we want to make the creator text a url, which could be cool but in that case the link text should be the creator name/s.)

## Additional context
See example email:

![image](https://user-images.githubusercontent.com/15254041/105067991-5aaa6f00-5a4e-11eb-9b38-ef0949aa2a92.png)

**Comment by HaSistrunk** [comment]
Clarification: I am only seeing the `Creator/s` label as part of the link in gmail, not in Outlook.

**Comment by helrond** [comment]
I think the second thing (hyperlinking the `Creator/s` label is happening because Gmail thinks that's part of the URL from the previous line. I've added a space before line breaks, which should resolve that issue, and also changed the label to `Creator(s)` so it looks less like it might be part of a URL path.

**Comment by helrond** [comment]
Reopening to address the first bullet point: Adding a line break after the message.
